FROM docker.io/golang:alpine

MAINTAINER Christoph Kappel <christoph@unexist.dev>

RUN apk add podman curl fuse-overlayfs \
    && sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf \
    && ln -s /usr/bin/podman /usr/bin/docker \
    && curl -sL --retry 2 https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
