stages:
    - build

default:
    before_script:
        - echo "$CI_REGISTRY_PASSWORD" | podman login --tls-verify=false -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

.dagger:
    image: golang:alpine
    before_script:
        - apk add podman curl fuse-overlayfs
        - sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf
        - ln -s /usr/bin/podman /usr/bin/docker
        - curl -sL --retry 3 https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
        - podman push $CI_REGISTRY_IMAGE:latest

build-deploy:
    stage: build
    extends: [ .dagger ]
    variables:
        DAGGER_PUBLISH: 1
        DAGGER_REGISTRY: $CI_REGISTRY
        DAGGER_IMAGE: todo-showcase
        DAGGER_TAG: 0.1
        BINARY_NAME: showcase
    script:
        - cd todo-service-gin && dagger run go run ci/main.go