stages:
    - build
    - deploy

.dagger:
    image: golang:alpine
    before_script:
        - apk add podman curl
        - rc-update add cgroups
        - rc-service cgroups start
        - cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
        - echo "$CI_REGISTRY_PASSWORD" | podman login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build-deploy:
    extends: [ .dagger ]
    script:
        - dagger run go run ci/main.go