ARG DAGGER_RUN_IMAGE
FROM ${DAGGER_RUN_IMAGE}

MAINTAINER Christoph Kappel <christoph@unexist.dev>

ARG BINARY_NAME a.out

RUN mkdir -p /app
COPY build/${BINARY_NAME} /app
WORKDIR /app

EXPOSE 8080

CMD ["./${BINARY_NAME}"]